version: '3.9'

services:
    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        container_name: "nginx"
        restart: unless-stopped
        ports:
            # These ports are in format <host-port>:<container-port>
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
            - '81:81' # Admin Web Port
        environment:
            DB_MYSQL_HOST: "db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "${MYSQL_USER}"
            DB_MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            DB_MYSQL_NAME: "nginx-proxy-manager"
        volumes:
            - nginxproxymanager:/data
            - letsencrypt:/etc/letsencrypt
            - ./logs/nginxproxymanager:/data/logs:consistent
            - ./php/www:/var/www/html:ro
        depends_on:
            - db
    db:
        image: 'jc21/mariadb-aria:latest'
        container_name: "db"
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "nginx-proxy-manager"
        volumes:
            - db:/var/lib/mysql
            - ./logs/mysql:/var/log:consistent
    php:
        build: ./php
        image: "php"
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ./php/www:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
        restart: unless-stopped
        depends_on:
            - nginx
            - db
    nodejs-app1:
        build: ./nodejs/www/app1
        image: "nodejs-app1"
        restart: unless-stopped
        ports:
            - '${NODEJS_APP1_PORT}:${NODEJS_APP1_PORT}'
        environment:
            NODE_PORT: "${NODEJS_APP1_PORT}"
            NODE_ENV: "${NODEJS_ENV}"
        volumes:
            - ./nodejs/www/app1:/usr/src/app
            - nodemodules-app1:/usr/src/app/node_modules
        user: node
volumes:
    nginxproxymanager:
    letsencrypt:
    db:
    nodemodules-app1: